# Site settings
title: With Regards To Software
url: "http://www.michali-k.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/blog" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  Thoughts on software

# Your information
email: michali@gmail.com
author: Michali Konstantinidis
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: A software engineer based in london
twitter_username: michalikon
github_username:  michali

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /:year/:month/:day/:title/
gems:
- jekyll-paginate
- jekyll-gist
- jemoji
- jekyll-archives
 
timezone: 'Europe/London'

jekyll-archives:
 enabled: 'all'
 layout: 'archive'
 permalinks:
   year: '/:year/'
   month: '/:year/:month/'
   day: '/:year/:month/:day/'
   tag: '/tag/:name/'
   category: '/category/:name/'
  
# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
