# Site settings
title: With Regards To Software
url: "http://www.michalikons.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: ""
description: >
  Thoughts on software

# Your information
email: michali@gmail.com
author: Michali Konstantinidis
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: A software engineer based in Sydney
twitter_username: michalikons
github_username:  michali

#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/

permalink: /:year/:month/:day/:title/
plugins_dir:
- jekyll-paginate
- jekyll-gist
- jemoji
- jekyll-archives
 
timezone: 'Australia/Sydney'

jekyll-archives:
 enabled: 'all'
 layout: 'archive'
 permalinks:
   year: '/:year/'
   month: '/:year/:month/'
   day: '/:year/:month/:day/'
   tag: '/tag/:name/'
   category: '/category/:name/'
  
# Build settings
gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
