# Site settings
title: Michali K
url: "http://www.michalikons.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: ""
description: >
  Thoughts on software

# Your information
email: michali@gmail.com
author: Michali K
avatar: "/assets/profile.jpg"
profile: A software engineer based in Sydney
twitter_username: michalikons
github_username:  michali

#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/

permalink: /blog/:year/:month/:day/:title/
plugins_dir:
- jekyll-paginate
- jekyll-gist
- jemoji
- jekyll-archives
 
timezone: 'Australia/Sydney'

jekyll-archives:
 enabled: 'all'
 layout: 'archive'
 permalinks:
   year: '/blog/:year/'
   month: '/blog/:year/:month/'
   day: '/blog/:year/:month/:day/'
   tag: '/blog/tag/:name/'
   category: '/blog/category/:name/'
  
# Build settings
gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 5
paginate_path: "blog/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
